services:
  frontenleads:
    image: darwinrobles/leadsfront:latest
    pull_policy: always
    container_name: leadsfront-contentent
    restart: always
    networks:
      - dokploy-network
    

networks:
  dokploy-network:
    external: true
